apiVersion: v1 
kind: PersistentVolumeClaim 
metadata: 
  name: nexus-pv-claim 
  namespace: devops-tools 
spec: 
  accessModes: 
    - ReadWriteOnce 
  resources: 
    requests: 
      storage: 50Gi 
--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus
  namespace: devops-tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nexus-server
  template:
    metadata:
      labels:
        app: nexus-server
    spec:
      containers:
        - name: nexus
          image: sonatype/nexus3:latest
          resources:
            limits:
              memory: "1Gi" 
              cpu: "1000m"
            requests:
              memory: "500Mi"
              cpu: "500m"
          ports:
            - containerPort: 8081
          volumeMounts:
            - name: nexus-data
              mountPath: /nexus-data
      volumes:
        - name: nexus-data
          persistentVolumeClaim:
            claimName: nexus-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: nexus
  namespace: devops-tools
spec:
  selector: 
    app: nexus-server
  type: NodePort  
  ports:
    - name: web
      port: 8081
      targetPort: 8081
      nodePort: 32003
    - name: group
      port: 8082
      targetPort: 8082
      nodePort: 32004
    - name: repo
      port: 8083
      targetPort: 8083
      nodePort: 32005
